version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "3000"
      SOCKET_HOST: "0.0.0.0"
      SOCKET_PORT: "5000"
      MONGO_URI: "mongodb://mongo:27017/"
      DB_NAME: "messages_db"
      COLLECTION_NAME: "messages"
    depends_on:
      - mongo
    volumes:
      - ./src/:/app/

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
